### ISSUE TITLE
thread 'main' panicked at 'slice index starts at  X but ends at Y ( X > Y)

### ISSUE THREAD

**Issue by dmestivier** [Ebedthan/hyperex#4]
Dear developers, 

Thank you for your very helpful work.

I ran `hyperex` on sequences from the SILVA (v138.1, U translated to T) database
on a Linux distribution (Ubuntu), using the binary distribution (v0.1.0) and also
the v0.1.1 from the `cargo` install.

Its works well at the beginning of the multifasta  but crashes at one
sequences and then stops (same issue, using the v0.1.0 or the v0.1.1)

The error message is the following:

```
thread 'main' panicked at 'slice index starts at 1388 but ends at 294', src/utils.rs:404:42
....
  26:     0x561cc0688038 - main
  27:     0x7f9b3f61c083 - __libc_start_main
  28:     0x561cc06163ca - _start
  29:                0x0 - <unknown>
Aborted (core dumped)
```

According to a previous Issues (#3), you mentionned that the sequence is in reverse
and if I understand well, version 0.1.1 should have corrected the problem.

Is it the case ? Or can you give some hints for correcting the bug for
people in fluent in rush ? for example, just how to skip the 
sequence without crash in order to get all other sequences processed ?

I have a toy sequence that I succeed to extract from the SILVA DB for testing 
the problem using the v1v2 region if needed.

```bash
$ ./hyperex-0.1.0/hyperex -V
hyperex 0.1.0
$ ./hyperex-0.1.0/hyperex --region v1v2  seq-that-failed-v1v2.fa --force 2> err
[13:53:02][INFO] This is hyperex v0.1.0
[13:53:02][INFO] Written by Anicet Ebou
[13:53:02][INFO] Available at https://github.com/Ebedthan/hyperex.git
[13:53:02][INFO] Localtime is 13:53:02
[13:53:02][INFO] You are dmestivier
[13:53:02][INFO] Operating system is Linux
[13:53:02][WARN] Overwriting hyperex_out.fa and hyperex_out.gff files
[13:53:02][INFO] Sequence type is DNA
[13:53:02][WARN] Sequence length is less than 1500 bp. We may not be able to find some regions
Aborted (core dumped)

$ ~/.cargo/bin/hyperex --region v1v2  seq-that-failed-v1v2.fa --force > out 2> err
Aborted (core dumped)

$ head -4 err
thread 'main' panicked at 'slice index starts at 1388 but ends at 294', /home/dmestivier/.cargo/registry/src/github.com-1ecc6299db9ec823/hyperex-0.1.1/src/utils.rs:404:42
stack backtrace:
   0:     0x5569312d33fb - std::backtrace_rs::backtrace::libunwind::trace::h909d8dc7fbe5a4dc
                               at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
```

Thank you for the great job and any for any ideas.
Sincerely yours
Denis

``` 


```

**Comment by Ebedthan** [comment]
Thanks @dmestivier
I'm working on a fix to be released soon :)

**Comment by dmestivier** [comment]
Dear developer, 

I try to something after reading a little big about RUST.
I add a test in the "utils.rs" file (line 391, hyperex 0.2.0) like this :+1: 

                           if !region.is_empty() {
                                  //dm <2022-07-30 sam.>: if sequence forward_start > reverse_start
                                  //==> CRASH
                                  // with 'thread 'main' panicked at 'slice index starts at X but ends at Y X>Y
                                  // We test and do not output such situation...
                                  if forward_start < reverse_start {
                                  fasta_writer.write_record(
                                      &fasta::Record::with_attrs(
                                          record.id(),
  
It works well and do not crash anymore. 

However, I am not sure of what to do for the other situations ( forward_start > reverse_start) and I am not sure that
it comes from an inverted sequence.

Sincerely yours,
denis

**Comment by Ebedthan** [comment]
Should be fixed in the latest release.

**Comment by masikol** [comment]
Hi!
Thank you for the tool, it’s great!

Unfortunately, hyperex version v0.2.0 panics with this exact error as well.

## My hyperex installation

I downloaded source code for hyperex 0.2.0 release from here: [https://github.com/Ebedthan/hyperex/archive/refs/tags/v0.2.0.tar.gz](https://github.com/Ebedthan/hyperex/archive/refs/tags/v0.2.0.tar.gz). Then I built it with `cargo build --release`

## My exact command
```bash
/home/cager-max/Soft/hyperex/hyperex-0.2.0/target/release/hyperex \
    -q \
    -p /mnt/tmp_buff/V3-V4_lame_tmp \
    -m 2 \
    --force \
    --forward CCTACGGGAGGCAGCAG \
    --reverse GACTACHVGGGTATCTAATCC \
    /mnt/data/Max/tmp/lame_16S_seq.fasta
```

## My input data

Please find attached a file named `lame_16S_seq.fasta.gz`. Gunzip it and here you are (GitHub won’t allow me to upload plain fasta).

[lame_16S_seq.fasta.gz](https://github.com/user-attachments/files/29964032/lame_16S_seq.fasta.gz)

## Hyperex stdout and stderr
```
here
here
here
[13:45:58][WARN] You have allowed 2 mismatch in the primer sequence
[13:45:58][WARN] Overwriting /mnt/tmp_buff/V3-V4_lame_tmp.fa and /mnt/tmp_buff/V3-V4_lame_tmp.gff files

thread 'main' (148557) panicked at src/utils.rs:322:29:
slice index starts at 1426 but ends at 778
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/01f6ddf7588f42ae2d7eb0a2f21d44e8e96674cf/library/std/src/panicking.rs:689:5
   1: core::panicking::panic_fmt
             at /rustc/01f6ddf7588f42ae2d7eb0a2f21d44e8e96674cf/library/core/src/panicking.rs:80:14
   2: core::slice::index::slice_index_fail::do_panic::runtime
             at /rustc/01f6ddf7588f42ae2d7eb0a2f21d44e8e96674cf/library/core/src/panic.rs:173:21
   3: core::slice::index::slice_index_fail::do_panic
             at /rustc/01f6ddf7588f42ae2d7eb0a2f21d44e8e96674cf/library/core/src/intrinsics/mod.rs:2449:9
   4: core::slice::index::slice_index_fail
             at /rustc/01f6ddf7588f42ae2d7eb0a2f21d44e8e96674cf/library/core/src/panic.rs:178:9
   5: <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/01f6ddf7588f42ae2d7eb0a2f21d44e8e96674cf/library/core/src/slice/index.rs:443:13
   6: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/01f6ddf7588f42ae2d7eb0a2f21d44e8e96674cf/library/core/src/slice/index.rs:19:15
   7: hyperex::utils::get_hypervar_regions
             at /home/cager-max/Soft/hyperex/hyperex-0.2.0/src/utils.rs:322:29
   8: hyperex::main
             at /home/cager-max/Soft/hyperex/hyperex-0.2.0/src/main.rs:41:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/01f6ddf7588f42ae2d7eb0a2f21d44e8e96674cf/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)
```

## A guess on the cause

There appear to be multiple binding sites for the forward primer on the template. Their coordinates are 338-354 and 1426-1443. And the reverse primer binds at 758-778.
I suppose 1426-1443 just appear after 338-354 in the search process, so hyperex takes 1426-1443, proceeds with slicing, and panics.

## Expected behaviour

I think it would be reasonable just to ignore binding sites of forward primers that are downstream of the reverse primer binding sites. And, respectively, to ignore reverse primer binding sites that are upstream of the forward primers binding sites.


Thanks for tour time,
Max
